name: CI
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
jobs:
  first_job:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml' # optional
      - name: Build with Maven
        run: mvn -B package --file pom.xml
